<?php
$goals = [
	['title' => '基礎知識', 'desc' => '掌握多媒體基本概念（影像、音訊、影格、編碼、壓縮）。'],
	['title' => '程式語言與框架', 'desc' => '能使用至少一種相關程式語言或框架（如 C++、JavaScript、Python、OpenCV、FFmpeg）。'],
	['title' => '影像處理', 'desc' => '執行影像載入、濾鏡、色彩轉換與邊緣偵測等處理。'],
	['title' => '音訊處理', 'desc' => '進行音訊讀取、播放、濾波與頻譜分析。'],
	['title' => '視訊處理', 'desc' => '讀寫視訊串流、擷取影格、簡單編輯與音視訊同步。'],
];
$json = json_encode($goals, JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);
?>
<!DOCTYPE html>
<html lang="zh-Hant">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>學習多媒體程式設計的目標</title>
	<style>body{font-family:Segoe UI,Arial,Helvetica,sans-serif;margin:20px}pre{background:#f5f5f5;padding:10px;border:1px solid #ddd}</style>
</head>
<body>
	<header><h1>學習多媒體程式設計的目標</h1></header>
	<main>
		<section>
			<h2>條列目標（由 PHP 產生）</h2>
			<ul>
				<?php foreach($goals as $g): ?>
					<li><strong><?php echo htmlspecialchars($g['title'], ENT_QUOTES, 'UTF-8'); ?>：</strong> <?php echo htmlspecialchars($g['desc'], ENT_QUOTES, 'UTF-8'); ?></li>
				<?php endforeach; ?>
			</ul>
		</section>
		<section>
			<h2>JSON 格式（PHP 變數）</h2>
			<pre id="phpJson"><?php echo $json; ?></pre>
		</section>
		<section>
			<h2>JavaScript 使用範例</h2>
			<p>按下按鈕後，會將 JSON 轉成物件並顯示於下方。</p>
			<button id="showBtn">顯示 JS 物件</button>
			<pre id="jsOut"></pre>
			<script>
				const data = <?php echo $json; ?>;
				document.getElementById('showBtn').addEventListener('click', () => {
					document.getElementById('jsOut').textContent = JSON.stringify(data, null, 2);
				});
			</script>
		</section>
	</main>
	<footer><p>Generated by index.php</p></footer>
</body>
</html>

